* 2011-05-10
** TODO 査定
*** 個人目標
B
B+
*** グループ目標
B-
C
*** 総合
B-
*** 自己コメント
サービス環境、開発環境の
開発のスタイルは問題なくなった
自分の開発のみに没頭することはなくなったと思う。
直接関わりの無いプロジェクトはどうしても理解が足りない。
サービスの情報全体をまとめるようなことをしたい。
積極的な参加。
責任。

月曜MTGのスタイルが変わったので、金曜月曜に開発陣のタスクを確認するようになった。
しかし直接関わりの無いプロジェクトはどうしても理解が足りない。
開発・運用全体を理解する態勢がまだまだ取れていないので、次期の課題としたい。

現状のコミュニケーションのスタイルには慣れてきたと思うが、アレアレと思うことがある。
「これ分からない」とすぐに云える状況に無い気がしている。原因は
** TODO 来期目標
*** 個人目標
グループ全体の状況を把握していること。
現行の各サービスを把握する。
*** グループ目標
各サービスをまとめる。
* 2011-04-22
** 集計 バッチ 会員情報
*** DBへ保存する。テーブルを作成
*** 集計 バッチとメールバッチ(メルマガ情報も一緒に送信)を別にする

*** テーブルカラム考

会員数（ponta） member

男性 male (members.gender
女性 female (members.gender

10代 age10 (members.birthday 換算するっぽ
20代 age20
30代 ..
40代
50代
60～

北海道（pref_id）pref01 (members.pref_code
・ pref02
・

職業 occupation (members.occupation_id
$C{OCCUPATIONS} = {
    1 => '会社員(派遣社員、アルバイト)',
    2 => '自営業',
    3 => '主婦',
    4 => '学生',
    5 => '無職',
    6 => 'その他'

サービスID service (member_services.service_id

[2011/04/19 16:26:28] Y.Uzumasa@Tokyo: 退会禁止区分じゃなくて、利用中サービス が入るはず。。
[2011/04/19 16:26:53] あかし:   30: レンタル　とかだよね。

** 管理画面権限

staff member (member_mask テンプレート制御)
✓ ✓

 会員管理(TAB)
   会員マスタ管理(LABEL)
     会員マスタ - / ○

 コンテンツ管理(TAB)
   キャンペーン管理(LABEL)
     キャンペーン管理 - / -
   クーポン管理(LABEL)
     クーポン管理 - / -

 お知らせ管理(TAB)
   TOPICS(LABEL)
     お知らせ（TOPICS）- / -

 マスタ管理(TAB)
   管理権限(LABEL)
     ユーザー情報 ○ / -
     権限ロール ○ / -

   店舗管理(LABEL)
     店舗マスタ - / -

 設定(TAB)
   設定(LABEL)
     基本設定 ○ / -

* 2011-04-19
**
** 集計 バッチ
*** GOLローカル新DBの内容を集計する
*** 結果はメール送信
hansokukikaku@geonet.co.jp (ゲオ販促部)
dev-geo@posren.com
*** 会員の集計情報は新DBへ保存

* 2011-04-18
** DONE SBM質問状

P0I0 株式会社ぽすれん(おすすめ映画情報ＤＶＤレンタル)

担当者様
お世話になっております、ぽすれんの増田です。

CP通知：
2011-sm0001「S!まとめて支払い」における暗号化強度変更について
こちらに関しまして幾つかご説明いただきたい点がございます。

1)
「暗号方式が制限される箇所」として、サポートサイトアクセスと、APIアクセスと両方挙げられておりますが。

サポートサイトアクセスについてはブラウザが対応している必要があるということでしょうか。その場合新しいバージョンのブラウザであればひとおおり問題ないという認識でよいでしょうか。

APIでのアクセスに関しましては、弊社側アクセス元HTTPサーバのSSLサーバ証明書の鍵長を2048bitにする等の変更が必要になるのでしょうか。
御社への接続なのでこちら側からはクライアントとしてのアクセスの話になるかと思うのですが、ここで弊社側システムのサーバ証明書が関連するのかどうかがよく分かりませんでした。

2)
「匿名SSLの暗号化方式」の使用もできなくなるということですが。
現在、試験環境(開発環境) のHTTPサーバは匿名のSSLサーバ証明書を使用してAPI接続させていただいておりますが、そちらも使用できなくなってしまうのでしょうか。

実際現状の弊社システムにおいて問題が発生するのかどうかの確認方法が良く分らず困っております。どこか参考にできる資料などございましたがお教えいただけますでしょうか。

何卒よろしくお願いいたします。

** DONE SBM質問考
*** クライアント、サーバ
**** SBMサーバへ接続するときのクライアントの問題
**** サポートサイトへのアクセスについてはブラウザが同暗号方式に対応しているかどうかということか
**** サーバからの接続の場合サーバ側のSSLサーバ証明書は関係なさそうだが、通信時問題となるのか
*** SSLサーバ証明書のバージョンアップが必要か
**** 鍵長2048bitの証明書が必要か
*** 開発環境
**** 匿名のサーバ証明書では接続できないとあるが、開発環境も?
*** 確認方法
**** マニュアルなど(URL) 教えてもらえるものはあるか
